title: Tower
subtitle: A Jekyll Theme
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: 关于我
      url: /about
    - text: 博客
      url: /blog
    - text: 照片墙
      url: /gallery

# Edit these details

author_logo: profile.png
author: Tower
author_bio: <p>喜欢挑战，渴望认知新的事物，并通过学习不断完善自己<P><h1>111<h2>
author_email: "soulmatew2015@gmail.com"
author_location: China
# author_website_url: "http://johndoe.com"
typewrite-text: Always On the Road.

author_work_experiences:
            - company_name: 友金所
              company_logo: work1.jpg
              company_url: https://www.yyfaxgroup.com/
              designation: 前端开发
              description: 贷款端产品开发
              visibility: true
            - company_name: 兔展
              company_logo: work2.jpg
              company_url: https://www.rabbitpre.com/
              designation: 前端开发
              description: 兔有米项目产品开发
              visibility: true
            - company_name: 菱歌科技
              company_logo: work3.jpg
              company_url: http://www.lingeyun.com/
              designation: 全栈开发
              description: 菱歌云管理平台开发
              visibility: true

author_education_details:
              - college_logo: education1.jpg
                college_name: 惠州学院
                college_degree: 电气工程及其自动化
                description: 管理学学士
                visibility: true             
              - college_logo: education2.jpg
                college_name: 华中科技大学
                college_degree: 计算机科学与技术
                description: 转学
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true

# social links
twitter_username: ''
github_username:  soulmate2015
facebook_username: ''
linkedin_username: ''
behance_username: ''
instagram_username: ''
medium_username: ''
telegram_username: ''
dribbble_username: ''
flickr_username: ''

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: ''
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

encoding: utf-8

destination: ./build
